### ISSUE TITLE
[TRACKER] Selection UI

### ISSUE THREAD

**Issue by chipsenkbeil** [chipsenkbeil/org-roam.nvim#1]
Tracker for implementing the selection UI. This is a general-purpose implementation located at `org-roam.core.ui.select`, which we will be able to use across the plugin to do things such as select nodes, tags, aliases, and more.

### Preview

<img width="499" alt="image" src="https://github.com/chipsenkbeil/org-roam.nvim/assets/2481802/4df70d80-fa23-47c7-86c1-6c6658e12e2d">

### Tasks

- [x] Callbacks: support a variety of callbacks for selecting, canceling, and changing.
- [x] Filter: text should be used to filter the item.
- [x] Rank: order of items should support being ranked (default is arbitrary order).
- [x] Filter Function: should be pluggable to support filtering & ranking in different ways.
- [x] Viewport: if we have more items than can fit in the window, we need a viewport to show a subset of those items. This viewport should shift as we move up or down the list, and resets to the top whenever we change the filter text or update the raw item list.
- [x] Custom highlights: we're leveraging the orgmode formatting, but it would be better (and safer) to have our own highlighting for a custom buffer type. This includes highlighting (different background color) the selected line alongside a unicode character to show highlighting. The character should be configurable.
- [x] Support neovim 0.10: detect 0.10, which introduces the `inline` virtual text position, which we use for our prompt. So if we see neovim 0.10, use that, otherwise default to what we have.
