### ISSUE TITLE
[TRACKER] org-roam buffer

### ISSUE THREAD

**Issue by chipsenkbeil** [chipsenkbeil/org-roam.nvim#2]
Tracker for implementing the [org-roam buffer](https://www.orgroam.com/manual.html#The-Org_002droam-Buffer). This is a general-purpose implementation located at `org-roam.ui.window.node-view`, which we will be able to use across the plugin to support [backlinks, reference links, and unlinked references widgets](https://www.orgroam.com/manual.html#Configuring-what-is-displayed-in-the-buffer).

### Preview

<img width="277" alt="image" src="https://github.com/chipsenkbeil/org-roam.nvim/assets/2481802/595756f5-335c-4d64-bc39-8cdc231a30ea">

### Tasks

- [x] Implement buffer & window wrappers to streamline implementation
- [x] Write widget to lookup backlinks and display by location
- [ ] Write widget to lookup reference links and display by location
- [ ] Write widget to lookup unlinked references and display by location
- [x] Overwrite link navigation to jump to another window (not the buffer window) before following the link
    - [x] Unclear if we need to overwrite the function (and how) or if we just provide a custom keymap
    - [x] Do we use orgmode to provide other navigation options? Or just have a custom buffer type w/ highlighting?
    - [x] If there is more than one other window, we need to provide an ability to select the window; we can use what has been written in #1, or do something like *TODO: insert example from some plugin that showed letters and select between them*
- [x] Support folding to more easily navigate
- [x] Support async loading of previews (if flagged as true)
    - [x] One liner preview? Or do we need to parse the entire file and pick the paragraph, list, etc. to show? If the latter, how much is shown? Need to see how org-roam does this, which appears to be more than just the line containing the link

**Comment by chipsenkbeil** [comment]
When navigating to a different buffer within the opened window, the toggle command to open/close the window still applies. We need to detect when the buffer for a window is changed from the original. Once it is, we need to disassociate toggling with that window.

**Comment by chipsenkbeil** [comment]
Implemented via #4. Using custom window picker for selection. nvim-orgmode's api to load files asynchronously. Custom expansion logic to only load previews on demand.

Skipping reference links and unlinked references for now.
