### ISSUE TITLE
[TRACKER] Templating support

### ISSUE THREAD

**Issue by chipsenkbeil** [chipsenkbeil/org-roam.nvim#5]
- [x] org-roam-node-find
- [x] org-roam-node-insert
- [x] org-roam-capture

Supporting roam capture templates is needed for all three of the above. I'm making these available through

- `org-roam.node.find`
- `org-roam.node.insert`
- `org-roam.node.capture`

The capture template leverages the newly-added `on_compile` to inject hooks into templates to prepend `:PROPERTIES:` with an id and `#+TITLE` to each newly-created roam file. In discussion right now, but I believe that I will need to check if the file exists, referenced by the `template.target` field, or `org_default_notes_file` if no target is supplied. In the case that it does exist, I will not want to prepend the properties or title again.

**Comment by chipsenkbeil** [comment]
Resolved by #8.
